TallerC/TallerC/Models/Circulo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TallerC.Models
{
    public class Circulo
    {
        public double radio { get; set; }
    }
}

TallerC/TallerC/Models/Cuadrado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TallerC.Models
{
    public class Cuadrado
    {
        public double lado { get; set; }
    }
}

TallerC/TallerC/Models/EdadPersona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TallerC.Models
{
    public class EdadPersona
    {
        public string nombre { get; set; }
        public string cedula { get; set; }
        public int edad { get; set; }
    }
}

TallerC/TallerC/Models/Numeros.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TallerC.Models
{
    public class Numeros
    {
        public int numero1 { get; set; }
        public int numero2 { get; set; }
    }
}

TallerC/TallerC/Models/NumerosConsecutivos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TallerC.Models
{
    public class NumerosConsecutivos
    {
        public int inicio { get; set; }
        public int fin { get; set; }
    }
}

TallerC/TallerC/Models/PesoRecomendado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TallerC.Models
{
    public class PesoRecomendado
    {
        public int altura { get; set; }
        public int edad { get; set; }
    }
}

TallerC/TallerC/Models/Rectangulo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TallerC.Models
{
    public class Rectangulo
    {
        public double baser  { get; set; }
        public double altura { get; set; }
    }
}

TallerC/TallerC/Models/Triangulo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TallerC.Models
{
    public class Triangulo
    {
        public double baset { get; set; }
        public double altura { get; set; }
    }
}

TallerC/TallerC/Controllers/CirculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TallerC.Models;

namespace TallerC.Controllers
{
    public class CirculoController : Controller
    {
        double pi = Math.PI;
        // GET: Circulo
        public ActionResult Index(Circulo circulotemp)
        {
            ViewBag.AreaCirculo = pi * Math.Pow(circulotemp.radio, 2);
            return View();
        }
    }
}

TallerC/TallerC/Controllers/CuadradoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TallerC.Models;

namespace TallerC.Controllers
{
    public class CuadradoController : Controller
    {
        // GET: Cuadrado
        public ActionResult Index(Cuadrado cuadradotemp)
        {
            double lado = cuadradotemp.lado;
            ViewBag.AreaCuadrado = lado * lado; 
            return View();
        }
    }
}

TallerC/TallerC/Controllers/EdadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TallerC.Models;

namespace TallerC.Controllers
{
    /*
    Dada el nombre, Cedula y edad en años de una persona mostrar su nombre, cedula y 
    equivalencia en meses, días, horas y minutos, además mostrar un mensaje que diga 
    si es mayor o menor de edad. (Mayor edad>=18). 
    */
    public class EdadController : Controller
    {
        //Equivalencias a un año
        int meses = 12;
        int dias = 365;
        int horas = 8760;
        int minutos = 525600;

        // GET: Eadad
        public ActionResult Index(EdadPersona edadpersonatemp)
        {
            int edad = edadpersonatemp.edad;
            ViewBag.EdadMeses = meses * edad;
            ViewBag.EdadDias = dias * edad;
            ViewBag.EdadHoras = horas * edad;
            ViewBag.EdadMinutos = minutos * edad;
            ViewBag.Edad = edad;
            return View();
        }
    }
}

TallerC/TallerC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TallerC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult IndexFiguras()
        {
            return View();
        }
    }
}

TallerC/TallerC/Controllers/NumerosConsecutivosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TallerC.Models;

namespace TallerC.Controllers
{
    public class NumerosConsecutivosController : Controller
    {
        string mensaje = "";

        // GET: NumerosConsecutivos
        public ActionResult Index(NumerosConsecutivos numconsetemp)
        {
            int ini = numconsetemp.inicio;
            int final = numconsetemp.fin;
            string resultado = "";
            if (ini <= final)
            {
                resultado = inicio(ini,final);
            }
            else
            {
                resultado = fin(ini, final);
            }

            ViewBag.Resultado = resultado;
            return View();
        }

        public string inicio(int inicio, int fin)
        {
            for (int i = inicio; i <= fin; i++)
            {
                mensaje += i + ", ";
            }
            return mensaje;
        }

        public string fin(int fin, int inicio)
        {
            for (int i = fin; i >= inicio; i--)
            {
                mensaje += i + ", ";
            }
            return mensaje;
        }
    }
}

TallerC/TallerC/Controllers/NumerosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TallerC.Models;

namespace TallerC.Controllers
{
    public class NumerosController : Controller
    {
        // GET: Numeros
        public ActionResult Index(Numeros numerostemp)
        {
            int numero1 = numerostemp.numero1, numero2 = numerostemp.numero2, resultado = 0;

            if (numero1 < numero2)
            {
                resultado = numero1 + numero2;
            }
            else if (numero1 > numero2)
            {
                resultado = numero1 - numero2;
            }
            else
            {
                resultado = numero1 * numero2;
            }

            ViewBag.Resultado = resultado;
            return View();
        }
    }
}

TallerC/TallerC/Controllers/PesoRecomendadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TallerC.Models;

namespace TallerC.Controllers
{
    public class PesoRecomendadoController : Controller
    {
        // GET: PesoRecomendado
        public ActionResult Index(PesoRecomendado pesotemp)
        {

            ViewBag.PesoRecomendado = (pesotemp.altura - 100 + pesotemp.edad / 10) * 0.9;
            return View();
        }
    }
}

TallerC/TallerC/Controllers/RectanguloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TallerC.Models;

namespace TallerC.Controllers
{ 
    public class RectanguloController : Controller
    {
        // GET: Rectangulo
        public ActionResult Index(Rectangulo rectangulotemp)
        {
            ViewBag.AreaRectangulo = rectangulotemp.altura * rectangulotemp.baser;
            return View();
        }
    }
}

TallerC/TallerC/Controllers/TrianguloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TallerC.Models;

namespace TallerC.Controllers
{
    public class TrianguloController : Controller
    {
        // GET: Triangulo
        public ActionResult Index(Triangulo triangulotemp)
        {
            ViewBag.AreaTriangulo = (triangulotemp.baset * triangulotemp.altura)/ 2;
            return View();
        }
    }
}

TallerC/TallerC/Views/Circulo/Index.cshtml
@model TallerC.Models.Circulo

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Circulo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.radio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.radio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.radio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<label>El areá es:</label> @ViewBag.AreaCirculo

<div>
    @Html.ActionLink("Regresar", "IndexFiguras", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TallerC/TallerC/Views/Cuadrado/Index.cshtml
@model TallerC.Models.Cuadrado

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cuadrado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.lado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<label>El areá es:</label> @ViewBag.AreaCuadrado

<div>
    @Html.ActionLink("Regresar", "IndexFiguras", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TallerC/TallerC/Views/Edad/Index.cshtml
@model TallerC.Models.EdadPersona

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EdadPersona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@{var mensaje = "";

    if (ViewBag.Edad >= 18)
    {
        mensaje = "Es mayor de edad";
    }
    else
    {
        mensaje = "Es menor de edad";
    }
}

<label>Edad en: </label>
<br>
<label>Meses: </label> @ViewBag.EdadMeses
<br>
<label>Dias: </label> @ViewBag.EdadDias
<br>
<label>Horas: </label> @ViewBag.EdadHoras
<br>
<label>Minutos: </label> @ViewBag.EdadMinutos
<br>
<label>@mensaje </label>
<br>
<div>
    @Html.ActionLink("Regresar", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TallerC/TallerC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>EJERCICIOS CON MVC</h1>
</div>

<div class="row">
</div>

TallerC/TallerC/Views/Home/IndexFiguras.cshtml
@{
    ViewBag.Title = "IndexFiguras";
}

<h2>IndexFiguras</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Area Figuras</h4>
        <hr />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Cuadrado" class="btn btn-default" onClick="location.href='/Cuadrado/Index'"  />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Rectangulo" class="btn btn-default" onClick="location.href='/Rectangulo/Index'"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Circulo" class="btn btn-default" onClick="location.href='/Circulo/Index'"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Triangulo" class="btn btn-default" onClick="location.href='/Triangulo/Index'"/>
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Regresar", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TallerC/TallerC/Views/Numeros/Index.cshtml
@model TallerC.Models.Numeros

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Numeros</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.numero1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numero2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<label>El resultado es:</label> @ViewBag.Resultado

<div>
    @Html.ActionLink("Regresar", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TallerC/TallerC/Views/NumerosConsecutivos/Index.cshtml
@model TallerC.Models.NumerosConsecutivos

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NumerosConsecutivos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<label>El resultado es:</label> @ViewBag.Resultado

<div>
    @Html.ActionLink("Regresar", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TallerC/TallerC/Views/PesoRecomendado/Index.cshtml
@model TallerC.Models.PesoRecomendado

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PesoRecomendado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.altura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.altura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.altura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<label>El peso ideal es:</label> @ViewBag.PesoRecomendado

<div>
    @Html.ActionLink("Regresar", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TallerC/TallerC/Views/Rectangulo/Index.cshtml
@model TallerC.Models.Rectangulo

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Rectangulo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.baser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.baser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.baser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.altura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.altura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.altura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<label>El areá es:</label> @ViewBag.AreaRectangulo

<div>
    @Html.ActionLink("Regresar", "IndexFiguras", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TallerC/TallerC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ejercicios con MVC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ejercicio con MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Edad", "Index", "Edad")</li>
                    <li>@Html.ActionLink("Area Figuras", "IndexFiguras", "Home")</li>
                    <li>@Html.ActionLink("Peso Ideal", "Index", "PesoRecomendado")</li>
                    <li>@Html.ActionLink("Numeros Consecutivos", "Index", "NumerosConsecutivos")</li>
                    <li>@Html.ActionLink("Numeros", "Index", "Numeros")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TallerC/TallerC/Views/Triangulo/Index.cshtml
@model TallerC.Models.Triangulo

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Triangulo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.baset, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.baset, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.baset, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.altura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.altura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.altura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<label>El areá es:</label> @ViewBag.AreaTriangulo


<div>
    @Html.ActionLink("Regresar", "IndexFiguras", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}